### ISSUE TITLE
Add font fallbacks

### ISSUE THREAD

**Issue by invisibleroads** [hellorahat/UNavMaze#1]
The `arial.ttf` font is not available by default in most Linux systems. Though possible, the installation of Microsoft fonts is somewhat cumbersome and slow (see https://www.linuxcapable.com/install-microsoft-fonts-on-fedora-linux).

Option 1: Use a fallback to a font that is available in Linux such as `NotoSans[wght].ttf` (run `find /usr/share/fonts -name *tf` to see available fonts)
```
try:
    font = ImageFont.truetype("arial.ttf", scale * .75)
except OSError:
    font = ImageFont.truetype("NotoSans[wght].ttf", scale * .75) 
```

Option 2: Include the `arial.ttf` in the repository in the same path as `run.py`

It is also possible to install the font for future use by the user by copying the font file to `~/.local/share/fonts`.

**Comment by hellorahat** [comment]
Thanks for the suggestions, I've added the fallback shown in option 1.

**Comment by invisibleroads** [comment]
Whoops, NotoSans[wght].ttf was not available on one of the machines.

Can you include `arial.ttf` directly in the repository?
